-- Add image_path to staff table
ALTER TABLE staff ADD COLUMN IF NOT EXISTS image_path VARCHAR(255) AFTER bio;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS name VARCHAR(100) AFTER id;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS email VARCHAR(100) AFTER name;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS phone VARCHAR(20) AFTER email;
